# General Values
# namespace:
# apiImage:
lbSSLCert: < your cert arn >
services:
  loadBalancer:
    name: apidevtest
    appName: kanvas-api

# namespace: memod-api
apiImage: < ecr repo > 

# PHP INIT Values
php:
  memoryLimit: 2128M


# Deployments Values
deployments:
  api:
    name: kanvas-api
    containerName: api
  queues:
    jobs:
      name: jobs-queue
      containerName: jobs-queue
    events:
      name: events-queue
      containerName: events-queue
    notifications:
      name: notifications-queue
      containerName: notifications-queue
    workflows:
      name: workflows-queue
      containerName: workflows-queue
    twitter:
      name: jobs-twitter-queue
      containerName: twitter-queue
  cron: 
    name: twitter
    containerName: cron-twitter
    schedule: "3 * * * *"
# Services Values

